### ISSUE TITLE
Uploaded my week 2 homework: Pollitics

### ISSUE THREAD

**Issue by mowoods** [mowoods/Pollitics#1]
Hey @codepathreview I uploaded my homework from week2. I added a hidden click on the top, where it says "Pollitics, small. I know this is not a good way of doing it, but I did it, after the fact.

**Comment by timothy1ee** [comment]
Great, thanks. Next time, can you include an animated gif using LICEcap? It usually only takes a moment to make the gif. I'm a big fan of this app, by the way. If you're interested in pursuing it, I can present it to the engineering class as an app to build.

The point of this homework was to practice replacing Keynote as a tool for prototyping. As you can see, it's pretty straightforward to make clickable screens using Xcode and Storyboard. Over the next few weeks, we're going to start adding in the fancy stuff.

For now, you should be able to:
- Navigate the files in Xcode.
- Collapse/expand the various panels.
- Run your project in the simulator.
- Add image assets.
- Create screens and connect them via buttons and a modal segue.
- Dismiss a modal segue in code.

**Comment by mowoods** [comment]
Hello @codepathreview I tried uploaded my TipCalculator, 3 times by accident on to Github, then I deleted them. Now, when trying to add it, via Github (Mac client), I get "MyTips doesn’t seem to exist at https://github.com/mowoods/TipsCalculator.git/ anymore. You may not have access, or it may have been deleted or renamed." You know what this means?

**Comment by timothy1ee** [comment]
Yeah, don't worry about that, it's not worth trying to fix. As long as you know how to use Github for future projects, you're good.
